os: linux
language: generic
sudo: required
dist: trusty
before_install:
  # Install Linuxbrew
  - test -d $HOME/.linuxbrew/bin || git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - npm install -g danger@alpha

script:
  - swift -version
  - brew install danger/tap/danger-swift
  - danger process danger-swift
